version: '3.3'


services:
#  api:
#    build:
#      context: ./app
#      dockerfile: Dockerfile
#    networks:
#      - database
#    #TODO: 任意のポートを以下に設定
#    ports:
#      - "????:????"

  mysql:
    image: 'mysql:5.7.22'
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: skymth_user
      MYSQL_PASSWORD: skymth_pass
      MYSQL_DATABASE: skymth_db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - database
    volumes:
      - "./mysql/conf:/docker-entrypoint-initdb.d"
      - db-data:/var/lib/mysql

    #TODO: 機械学習環境、フロント環境を追加


volumes:
  db-data:

networks:
  database:
