version: '3.3'


services:
  mysql:
    image: 'mysql:5.7.22'
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: skymth_user
      MYSQL_PASSWORD: skymth_pass
      MYSQL_DATABASE: skymth_db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - database
    volumes:
      - "./mysql/conf:/docker-entrypoint-initdb.d"
      - db-data:/var/lib/mysql

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - apiserver
    volumes:
      - .:/app/frontend
      - /app/frontend/node_modules

  api:
    build:
      context: ./DockerV
      dockerfile: Dockerfile

    ports:
      - "3000:3000"
    networks:
      - database
      - apiserver


volumes:
  db-data:

networks:
  database:
  apiserver:

