version: '3.3'


services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    networks:
      - database
    links:
      - mysql
      - api
    volumes:
      - $PWD:/root
    tty: true

  api:
    build:
      context: ./DockerV
      dockerfile: Dockerfile

    ports:
      - "3000:3000"
    networks:
      - database
    links:
      - mysql
    volumes:
      - $PWD/:/root
    tty: True

  mysql:
    image: 'mysql:5.7.22'
    ports:
      - "3306:3306"
    hostname: mysql
    environment:
      MYSQL_USER: skymth_user
      MYSQL_PASSWORD: skymth_pass
      MYSQL_DATABASE: skymth_db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - database
    volumes:
      - "./mysql/conf:/docker-entrypoint-initdb.d"
      - db-data:/var/lib/mysql

    #TODO: 機械学習環境、フロント環境を追加


volumes:
  db-data:

networks:
  database:
